version: '2'
services:
  code:
    build: .
    image: sistemacode/code
    environment:
      RAILS_ENV: development
      PGDBNAME: code_development
    volumes:
      - .:/app
      - ./db/data:/var/lib/postgresql
    ports:
      - "8080:80"
