source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '5.0.0'
gem 'alert_message'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'bootstrap-generators', git: 'https://github.com/decioferreira/bootstrap-generators.git'
gem 'bootstrap-wysihtml5-rails'
gem 'bootstrap-wysihtml5-rails-font-awesome', '~> 0.3.1.25'
gem 'carrierwave'
gem 'cancancan'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'figaro'
gem 'kaminari'
gem 'kaminari-bootstrap', '~> 3.0.1'
gem 'kaminari-i18n'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'mini_magick'
gem 'modernizr-rails'
gem 'pdfkit'
gem 'rails-i18n'
gem 'rails-env'
gem 'randumb'
gem 'rails4-autocomplete'
gem 'responders'
gem 'sass-rails', '~> 5.0'
gem 'search_cop'
gem 'sprockets-rails', :require => 'sprockets/railtie'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'wkhtmltopdf-binary'
gem 'record_tag_helper', '~> 1.0'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rails_db_info'
  gem 'capybara'
  gem 'email_spec'
  gem 'database_rewinder'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'mina'
  gem 'rspec-rails', '~> 3.4'
  gem 'rails-controller-testing'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers', '~> 3.0', require: false
  gem 'spring'
  gem 'simplecov',            '0.11.1', require: false
end

group :staging, :production do
  gem 'passenger'
  gem 'pg'
  gem 'mini_racer'
end
