development: &dev
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: code_dev
  pool: 5
  username: postgres
  password: postgres

test: &test
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: code_test
  pool: 5
  username: postgres
  password: postgres

staging:
  <<: *dev

production:
    host: <%= ENV['PGHOST'] %>
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['PGDBNAME'] %>
    pool: 5
    username: <%= ENV['PGUSERNAME'] %>
    password: <%= ENV['PGPASSWORD'] %>
